version: '3.8'
services:
  feedback-api:
    build: .
    container_name: api
    depends_on:
      - 'database'
    ports:
      - '8080:8080'
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
